### ISSUE TITLE
MilkyWay_DR0.5_DZ0.1_DPHI10_RMAX20_ZMAX5_galprop_format.fits.gz

### ISSUE THREAD

**Issue by Michael270595** [cosmicrays/DRAGON#1]
Hi, I've installed DRAGON in Ubuntu. When i was trying to know the output by typing ./DRAGON examples/run_2D.xml. The output is just like this:

Reading input from examples/run_2D.xml ... 
... observer is sitting at x = 8.3 y = 0 z = 0
... using the same injection index for all species from the XML file!
1.85 
1.85 

... input file read successfully!

Begin of DRAGON constructor.

Getting the nuclei list ...
... done!

Initializing the Galaxy ...
... file examples/run_2D.source.param does not exist. Using config_files/template.source.param!
... reading source.param table with 71 rows!
... grid done!
... geometry done!
... gas done!
... all astrophysical sources done!
... diffusion coefficient done!

FITSIO status = 104: could not open the named file
failed to find or open the following file: (ffopen)
data/MilkyWay_DR0.5_DZ0.1_DPHI10_RMAX20_ZMAX5_galprop_format.fits.gz

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 104: could not open the named file

FITSIO status = 115: NULL input pointer
Segmentation fault (core dumped)

I've downloaded MilkyWay_DR0.5_DZ0.1_DPHI10_RMAX20_ZMAX5_galprop_format.fits.gz from https://gitgud.io/Hamstah/DRAGON/blob/master/data/MilkyWay_DR0.5_DZ0.1_DPHI10_RMAX20_ZMAX5_galprop_format.fits.gz

But till now I can't run the dragon. Please help me :) and thank you.

**Comment by carmeloevoli** [comment]
hi, did you put in the DATA/ folder?
you should also create an output/ folder.

**Comment by Michael270595** [comment]
I've done it and now the Dragon is working! Thank you for your help.
