### ISSUE TITLE
Cannot find cfitsio library

### ISSUE THREAD

**Issue by jtbuch** [cosmicrays/DRAGON#2]
Hi,

I'm trying to set up DRAGON on my Mac OS 10.12.6 . While trying to execute the ./configure command as

`./configure --with-cfitsio=/usr/local/ --with-gsl-path=/usr/local/Cellar/gsl/2.4/bin --with-numcpu=4`

I'm getting the following error: `Cannot find cfitsio library`

This is surprising since the relevant cfitsio files are present in `/usr/local/include` and `/usr/local/lib` as required by the example command in the Readme file.

Not sure where I'm making a mistake here. Any help will be appreciated!

**Comment by carmeloevoli** [comment]
hi, it seems you are doing correctly.

Could you please check that fitsio.h is in /usr/local/include/ and libcfitsio.a is in /usr/local/lib?

Did you use the ./start.sh before confirue?

**Comment by jtbuch** [comment]
Hi Carmelo,

Thanks for getting back to me on this promptly.

> Could you please check that fitsio.h is in /usr/local/include/ and libcfitsio.a is in /usr/local/lib?

Yes, these files are present in the appropriate folders.

> Did you use the ./start.sh before configure?

Yes, it gives me the following result:
`Preparing the system to install...
./start.sh: line 4: aclocal: command not found
./start.sh: line 5: libtoolize: command not found
./start.sh: line 6: automake: command not found
./start.sh: line 7: autoconf: command not found
Done. Run the configure script to set up the makefiles`

Here's a pastebin link of the config.log that's generated if it's helpful: https://pastebin.com/HH8Utxv0

I've been able to run DRAGON successfully before in a Linux environment, so I'm wondering whether
this is one of those Mac compatibility issues.

 Thanks again for your help!

Jatan

**Comment by carmeloevoli** [comment]
it seems that you don't have automake tools installed, try with [homebrew](https://brew.sh) to install them on a Mac

**Comment by jtbuch** [comment]
Hi Carmelo,

There's still some pesky issues, but pretty sure it's a problem on my end. Fortunately, I've run into Daniele at TeVPA and he's very kindly agreed to help me out here. 

Thanks so much for your help!

Best,
Jatan

**Comment by carmeloevoli** [comment]
Great!
